openapi: 3.1.0
info:
  title: UserService
  version: 1.0.0
paths:
  /register:
    post:
      summary: Register
      operationId: register_register_post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserCreate'
        required: true
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /login:
    post:
      summary: Login
      operationId: login_login_post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserAuth'
        required: true
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Token'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /me:
    get:
      summary: Whoami
      operationId: whoami_me_get
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
  /wait:
    get:
      summary: Whoami
      operationId: whoami_wait_get
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
  /me/update:
    put:
      summary: Whoami
      operationId: whoami_me_update_put
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserUpdate'
        required: true
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
components:
  schemas:
    HTTPValidationError:
      properties:
        detail:
          items:
            $ref: '#/components/schemas/ValidationError'
          type: array
          title: Detail
      type: object
      title: HTTPValidationError
    Token:
      properties:
        access_token:
          type: string
          title: Access Token
      type: object
      required:
      - access_token
      title: Token
    UserAuth:
      properties:
        login:
          type: string
          title: Login
        password:
          type: string
          title: Password
      type: object
      required:
      - login
      - password
      title: UserAuth
    UserCreate:
      properties:
        email:
          type: string
          format: email
          title: Email
        password:
          type: string
          title: Password
        login:
          type: string
          title: Login
      type: object
      required:
      - email
      - password
      - login
      title: UserCreate
    UserUpdate:
      properties:
        first_name:
          type: string
          title: First Name
          default: ''
        last_name:
          type: string
          title: Last Name
          default: ''
        phone_number:
          type: string
          pattern: ^\+?[1-9]\d{1,14}$
          title: Phone Number
        birth_date:
          type: string
          format: date-time
          title: Birth Date
          default: '2025-03-07T19:41:27.218203Z'
        email:
          type: string
          format: email
          title: Email
          default: ''
      type: object
      required:
      - phone_number
      title: UserUpdate
    ValidationError:
      properties:
        loc:
          items:
            anyOf:
            - type: string
            - type: integer
          type: array
          title: Location
        msg:
          type: string
          title: Message
        type:
          type: string
          title: Error Type
      type: object
      required:
      - loc
      - msg
      - type
      title: ValidationError
