# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: post.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'post.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\npost.proto\x12\x04post\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x19google/protobuf/any.proto\"\x15\n\x04UUID\x12\r\n\x05value\x18\x01 \x01(\t\"\xd5\x01\n\x04Post\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x65sc\x18\x02 \x01(\t\x12(\n\x04\x64\x61te\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12/\n\x0bupdate_date\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x0f\n\x07private\x18\x05 \x01(\x08\x12\x0c\n\x04tags\x18\x06 \x03(\t\x12\x18\n\x04uuid\x18\x07 \x01(\x0b\x32\n.post.UUID\x12\x1d\n\tuuid_user\x18\x08 \x01(\x0b\x32\n.post.UUID\"d\n\rUpdatePostMsg\x12\x18\n\x04uuid\x18\x01 \x01(\x0b\x32\n.post.UUID\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0c\n\x04\x64\x65sc\x18\x03 \x01(\t\x12\x0f\n\x07private\x18\x04 \x01(\x08\x12\x0c\n\x04tags\x18\x05 \x03(\t\"T\n\x0cPostResponse\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\x12\x0f\n\x07message\x18\x02 \x01(\t\x12%\n\x07\x64\x65tails\x18\x03 \x03(\x0b\x32\x14.google.protobuf.Any2\xe3\x01\n\x05Posts\x12,\n\nCreatePost\x12\n.post.Post\x1a\x12.post.PostResponse\x12,\n\nDeletePost\x12\n.post.UUID\x1a\x12.post.PostResponse\x12\x35\n\nUpdatePost\x12\x13.post.UpdatePostMsg\x1a\x12.post.PostResponse\x12!\n\x07GetById\x12\n.post.UUID\x1a\n.post.Post\x12$\n\x08GetPosts\x12\n.post.UUID\x1a\n.post.Post0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'post_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_UUID']._serialized_start=80
  _globals['_UUID']._serialized_end=101
  _globals['_POST']._serialized_start=104
  _globals['_POST']._serialized_end=317
  _globals['_UPDATEPOSTMSG']._serialized_start=319
  _globals['_UPDATEPOSTMSG']._serialized_end=419
  _globals['_POSTRESPONSE']._serialized_start=421
  _globals['_POSTRESPONSE']._serialized_end=505
  _globals['_POSTS']._serialized_start=508
  _globals['_POSTS']._serialized_end=735
# @@protoc_insertion_point(module_scope)
